import java.lang.RuntimeException

fun main(args: Array<String>) {
    



}